### PR TITLE
guile-dbi: no need to use guile-config, GUILE_* macros already used

### PR DESCRIPTION
**Pull request by aconchillo**

### CODE REVIEW

**Comment by linas** [comment]
Thanks!

Question: while testing this, I spotted some very unexpected errors:
```
checking for guile-3.0... yes
../configure: line 20324: GUILE_PKG: command not found
../configure: line 20325: GUILE_FLAGS: command not found
../configure: line 20326: GUILE_SITE_DIR: command not found
```

Despite this, everything seemed to build OK. I'm trying to find the root cause of these messages now. Do you have any wise words of wisdom?

**Comment by linas** [comment]
Those lines were added to fix #6 and #7 and so this pull req partly undoes that fix. I'm confused. I'm guessing there is some distro dependency in all of this.

**Comment by aconchillo** [comment]
> Thanks!
> 
> Question: while testing this, I spotted some very unexpected errors:
> 
> ```
> checking for guile-3.0... yes
> ../configure: line 20324: GUILE_PKG: command not found
> ../configure: line 20325: GUILE_FLAGS: command not found
> ../configure: line 20326: GUILE_SITE_DIR: command not found
> ```
> 
> Despite this, everything seemed to build OK. I'm trying to find the root cause of these messages now. Do you have any wise words of wisdom?

Interesting. Those macros are from `guile.m4` which should come with Guile and is usually installed in `/usr/share/aclocal`.

**Comment by aconchillo** [comment]
> Those lines were added to fix #6 and #7 and so this pull req partly undoes that fix. I'm confused. I'm guessing there is some distro dependency in all of this.

Before, in your system, since it couldn't find `GUILE_PKG`, etc. it just ran the `guile-config` lines and it was fine. But in a properly installed system you should have the macros available.

My guess is that maybe you have installed Guile manually (maybe in `/usr/local/`) and the `guile.m4` file ends up in `/usr/local/share/aclocal` which the system `automake` is not able to find unless you specify `ACLOCAL_PATH` environment variable.

**Comment by linas** [comment]
never mind. Ignore last comments. I think I got it under control, now.

**Comment by aconchillo** [comment]
> never mind. Ignore last comments. I think I got it under control, now.

Cool. I might be sending more PRs in the near future. Trying to get a bunch of libraries working again with Guile Homebrew. https://github.com/aconchillo/homebrew-guile.

**Pull request merged**
