### PR TITLE
Update multiple autoconf files

### PR DESCRIPTION
**Pull request by linas**
Work in progress.

### CODE REVIEW

**Review by linas — COMMENTED** [review]
Hi I just noticed you did a lot of work to update the configure files, but you never opened a pull request to merge them.  I just now opened such a pull req, but I would like your comments before I do anything more. Ping @tmtvl

**Comment by mwette** [comment]
ping - hoping this fixes some issues I'm having

**Comment by linas** [comment]
I'll try to look at this tomorrow. What issues are you having?

**Comment by mwette** [comment]
```
guile-dbd-mysql.c:24:10: fatal error: guile-dbi/guile-dbi.h: No such file or directory
   24 | #include <guile-dbi/guile-dbi.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
```
the dbi was not found under ``/opt/local/include`` even though prefix is ``/opt/local``.   CFLAGS did include ``/opt/local/include/guile/3.0/`` by the way.

And I don't see an issues tab on your repo.   I'm not sure what that is about.   Something you can control?

**Comment by linas** [comment]
> guile-dbi/guile-dbi.h: No such file or directory

Did you `make install` after building guile-dbi?  For me, using all the defaults, it appears at ` /usr/local/include/guile-dbi/guile-dbi.h`

**Comment by linas** [comment]
Anyway, I've now merged this pull req.

**Comment by mwette** [comment]
I did the make install.   The problem was that no -I argument pointed to the includes.  Adding ``-I/opt/local/include`` to the makefile by hand got it to work.

**Comment by linas** [comment]
> The problem was that no -I argument pointed to the includes.

We should be discussing this in a brand new bug report, and not here, but .. whatever.

Let me see if I understand this correctly: you over-wrote the default install path with
```
configure --prefix=/opt/local
```
or similar, then a `make; make install` and then you discover that DBD cannot find the include files for DBI?

Hmm. Well, I suppose that's fixable. I have to say, I am not very motivated to work on this, though. So if you have a wild hair and need to get this all set up just right (set up your hair?) ... a pull request would not be rejected.

**Pull request merged**
